# 异常

Throwable 是所有错误和异常的超类

错误：很严重，无法处理，只能避免
异常：可以通过处理正常运行

Excption：编译器异常，进行编译（写代码）出现的问题
    RuntimeException：运行期异常，java程序运行过程中出现的问题

throws

try-catch

## 异常产生过程的解析

```
public class Demo02Exception{
    public static void main(String[] args){
        int[] arr = {1,2,3};
        int e = getElement(arr,3);
        Sout(e)
    }

    public static int getElement(int[] arr,int index){
        int ele = arr[index];
        return ele;
    }
}
```

数组长度为3，index为3发生了数组越界，JVM会做两件事：
1. JVM会根据异常产生的原因创建一个异常对象new ArrayIndexOutOfBound("3);,这个异常对象包含了一场产生的（`内容,原因，位置`）
2. 在getElement方法中没有异常处理逻辑(try catch),那么jvm就会把异常对象抛出给方法的调用者main来处理这个异常
3. main也没有异常处理逻辑，那么就会抛出到main的调用者jvm去处理
4. jvm把异常对象（内容，原因，位置）以红色字体打印出来，并中断当前正在执行的程序

## throw关键字

可以使用throw关键字在`指定的方法`中抛出`指定的异常`

使用格式:
    throw new xxException("异常产生的原因");

注意：
1. 必须在方法的内部
2. new的对象必须是Exception或者其子类
3. throw关键字抛出指定的异常对象，我们就必须处理这个异常对象

## Objects费控判断
```
public static<T> T requireNonNull(T obj){
    if(obj == null)
        throw new NullPointerException("传递的对象的值时null");
    return obj;
}

```

## 声明异常对象throws

异常处理的第一种方式：交给别人处理

在方法声明时使用：

修饰符 返回值类型 方法名(参数列表) throws AAAException,BBBException{
    throw new AAAException();
    ...
}

注意
1. 必须在方法声明处
2. Exception或其子类
3. 方法内部抛出多个，throws多个
    如有，可抛出它们共同父类
4. 调用了一个抛出异常的方法，就必须处理声明的异常

## try-catch

try{
    可能产生异常的代码
}catch(定义一个异常变量，接收try中抛出的异常){
    异常的处理逻辑;
}
...
catch(xxException e){

}
`有先后顺序`，`子类在上面，父类在下面（必须）`

## Throwable中3个异常处理的方法

- String getMessage()返回此throwable的简短描述
- String toString() 返回throwable的详细消息字符串
- void printstackTrace() jvm打印异常对象，默认方法，最全面

## finally代码块

有些程序无论如何都要执行：用finally

比如资源释放

如果finally有return语句，永远返回finally中的结果，避免该情况

## 子父类异常注意

如果父类抛出多个异常，子类重写父类方法时，抛出`和父类相同`的异常或者是父类`异常的子类`，或者`不抛出异常`。（`有且只有这三种`）

父类方法没有抛出异常，子类重写父类该方法时，也不可抛出异常，此时子类`产生该异常，只能捕获处理`，不能声明抛出

## 自定义异常

![在这里插入图片描述](https://img-blog.csdnimg.cn/20191003103347325.jpg?x-oss-process=image/watermark,type_ZmFuZ3poZW5naGVpdGk,shadow_10,text_aHR0cHM6Ly9ibG9nLmNzZG4ubmV0L2EyNDUyOTMyMDY=,size_16,color_FFFFFF,t_70)

